
		dc.l Obj_Ring							; 0	;Unusable Object ID in S2
		dc.l Delete_Current_Sprite				; 1	;Sonic Object in S2
		dc.l Delete_Current_Sprite				; 2 ;Tails Object in S2
		dc.l Obj_PathSwap						; 3
		dc.l Delete_Current_Sprite				; 4 ;Water Surface
		dc.l Delete_Current_Sprite				; 5 ;Tails' Tails
		dc.l Obj06								; 6 ;EHZ/MTZ Spiral Run Object
		dc.l Delete_Current_Sprite				; 7 ;OOZ Oil
		dc.l Delete_Current_Sprite				; 8 ;Spindash Dust/Water Splash
		dc.l Delete_Current_Sprite				; 9 ;Special Stage Sonic
		dc.l Delete_Current_Sprite				; A ;Small Bubbles
		dc.l Delete_Current_Sprite				; B ;CPZ Tipping Pipe
		dc.l Delete_Current_Sprite				; C ;Unused Platform
		dc.l Pacca_TemporarySignpost			; D ;End of Level Signpost (no equivalent in S3K due to Miniboss system!)
		dc.l Delete_Current_Sprite				; E ;Title Screen Intro Anim
		dc.l Delete_Current_Sprite				; F ;Title Screen Menu
		dc.l Delete_Current_Sprite				; 10 ;Special Stage Tails
		dc.l Obj_TensionBridge					; 11
		dc.l Delete_Current_Sprite				; 12
		dc.l Delete_Current_Sprite				; 13
		dc.l Delete_Current_Sprite				; 14
		dc.l Delete_Current_Sprite				; 15
		dc.l Delete_Current_Sprite				; 16
		dc.l Delete_Current_Sprite				; 17
		dc.l Obj_FloatingPlatform				; 18
		dc.l Delete_Current_Sprite				; 19
		dc.l Obj_CollapsingPlatform				; 1A
		dc.l Delete_Current_Sprite				; 1B
		dc.l Delete_Current_Sprite				; 1C
		dc.l Delete_Current_Sprite				; 1D
		dc.l Delete_Current_Sprite				; 1E
		dc.l Delete_Current_Sprite				; 1F
		dc.l Delete_Current_Sprite				; 20
		dc.l Delete_Current_Sprite				; 21
		dc.l Delete_Current_Sprite				; 22
		dc.l Delete_Current_Sprite				; 23
		dc.l Obj_Bubbler						; 24
		dc.l Obj_Ring							; 25
		dc.l Obj_Monitor						; 26
		dc.l Delete_Current_Sprite				; 27
		dc.l Obj_InvisibleBlock					; 28
		dc.l Delete_Current_Sprite				; 29
		dc.l Delete_Current_Sprite				; 2A
		dc.l Delete_Current_Sprite				; 2B
		dc.l Delete_Current_Sprite				; 2C
		dc.l Delete_Current_Sprite				; 2D
		dc.l Delete_Current_Sprite				; 2E
		dc.l Delete_Current_Sprite				; 2F
		dc.l Delete_Current_Sprite				; 30
		dc.l Obj_S2LavaMarker					; 31
		dc.l Delete_Current_Sprite				; 32
		dc.l Delete_Current_Sprite				; 33
		dc.l Delete_Current_Sprite				; 34
		dc.l Delete_Current_Sprite				; 35
		dc.l Obj_Spikes							; 36
		dc.l Delete_Current_Sprite				; 37
		dc.l Delete_Current_Sprite				; 38
		dc.l Delete_Current_Sprite				; 39
		dc.l Delete_Current_Sprite				; 3A
		dc.l Delete_Current_Sprite				; 3B
		dc.l Delete_Current_Sprite				; 3C
		dc.l Delete_Current_Sprite				; 3D
		dc.l Delete_Current_Sprite				; 3E
		dc.l Delete_Current_Sprite				; 3F
		dc.l Delete_Current_Sprite				; 40
		dc.l Obj_Spring							; 41
		dc.l Delete_Current_Sprite				; 42
		dc.l Delete_Current_Sprite				; 43
		dc.l Delete_Current_Sprite				; 44
		dc.l Delete_Current_Sprite				; 45
		dc.l Delete_Current_Sprite				; 46
		dc.l Delete_Current_Sprite				; 47
		dc.l Delete_Current_Sprite				; 48
		dc.l Delete_Current_Sprite				; 49
		dc.l Delete_Current_Sprite				; 4A
		dc.l Obj_Buzzer							; 4B
		dc.l Delete_Current_Sprite				; 4C
		dc.l Delete_Current_Sprite				; 4D
		dc.l Delete_Current_Sprite				; 4E
		dc.l Delete_Current_Sprite				; 4F
		dc.l Delete_Current_Sprite				; 50
		dc.l Delete_Current_Sprite				; 51
		dc.l Delete_Current_Sprite				; 52
		dc.l Delete_Current_Sprite				; 53
		dc.l Delete_Current_Sprite				; 54
		dc.l Delete_Current_Sprite				; 55
		dc.l Delete_Current_Sprite				; 56
		dc.l Delete_Current_Sprite				; 57
		dc.l Delete_Current_Sprite				; 58
		dc.l Delete_Current_Sprite				; 59
		dc.l Delete_Current_Sprite				; 5A
		dc.l Delete_Current_Sprite				; 5B
		dc.l Delete_Current_Sprite				; 5C
		dc.l Delete_Current_Sprite				; 5D
		dc.l Delete_Current_Sprite				; 5E
		dc.l Delete_Current_Sprite				; 5F
		dc.l Delete_Current_Sprite				; 60
		dc.l Delete_Current_Sprite				; 61
		dc.l Delete_Current_Sprite				; 62
		dc.l Delete_Current_Sprite				; 63
		dc.l Delete_Current_Sprite				; 64
		dc.l Delete_Current_Sprite				; 65
		dc.l Delete_Current_Sprite				; 66
		dc.l Delete_Current_Sprite				; 67
		dc.l Delete_Current_Sprite				; 68
		dc.l Delete_Current_Sprite				; 69
		dc.l Delete_Current_Sprite				; 6A
		dc.l Delete_Current_Sprite				; 6B
		dc.l Delete_Current_Sprite				; 6C
		dc.l Delete_Current_Sprite				; 6D
		dc.l Delete_Current_Sprite				; 6E
		dc.l Delete_Current_Sprite				; 6F
		dc.l Delete_Current_Sprite				; 70
		dc.l Delete_Current_Sprite				; 71
		dc.l Delete_Current_Sprite				; 72
		dc.l Delete_Current_Sprite				; 73
		dc.l Obj_InvisibleBlock					; 74
		dc.l Delete_Current_Sprite				; 75
		dc.l Delete_Current_Sprite				; 76
		dc.l Delete_Current_Sprite				; 77
		dc.l Delete_Current_Sprite				; 78
		dc.l Obj_StarPost						; 79
		dc.l Delete_Current_Sprite				; 7A
		dc.l Delete_Current_Sprite				; 7B
		dc.l Delete_Current_Sprite				; 7C
		dc.l Delete_Current_Sprite				; 7D
		dc.l Delete_Current_Sprite				; 7E
		dc.l Delete_Current_Sprite				; 7F
		dc.l Delete_Current_Sprite				; 80
		dc.l Delete_Current_Sprite				; 81
		dc.l Delete_Current_Sprite				; 82
		dc.l Delete_Current_Sprite				; 83
		dc.l Delete_Current_Sprite				; 84
		dc.l Delete_Current_Sprite				; 85
		dc.l Delete_Current_Sprite				; 86
		dc.l Delete_Current_Sprite				; 87
		dc.l Delete_Current_Sprite				; 88
		dc.l Delete_Current_Sprite				; 89
		dc.l Delete_Current_Sprite				; 8A
		dc.l Delete_Current_Sprite				; 8B
		dc.l Delete_Current_Sprite				; 8C
		dc.l Delete_Current_Sprite				; 8D
		dc.l Delete_Current_Sprite				; 8E
		dc.l Delete_Current_Sprite				; 8F
		dc.l Delete_Current_Sprite				; 90
		dc.l Delete_Current_Sprite				; 91
		dc.l Delete_Current_Sprite				; 92
		dc.l Delete_Current_Sprite				; 93
		dc.l Delete_Current_Sprite				; 94
		dc.l Delete_Current_Sprite				; 95
		dc.l Delete_Current_Sprite				; 96
		dc.l Delete_Current_Sprite				; 97
		dc.l Delete_Current_Sprite				; 98
		dc.l Delete_Current_Sprite				; 99
		dc.l Delete_Current_Sprite				; 9A
		dc.l Delete_Current_Sprite				; 9B
		dc.l Delete_Current_Sprite				; 9C
		dc.l Delete_Current_Sprite				; 9D
		dc.l Delete_Current_Sprite				; 9E
		dc.l Delete_Current_Sprite				; 9F
		dc.l Delete_Current_Sprite				; A0
		dc.l Delete_Current_Sprite				; A1
		dc.l Delete_Current_Sprite				; A2
		dc.l Delete_Current_Sprite				; A3
		dc.l Delete_Current_Sprite				; A4
		dc.l Delete_Current_Sprite				; A5
		dc.l Delete_Current_Sprite				; A6
		dc.l Delete_Current_Sprite				; A7
		dc.l Delete_Current_Sprite				; A8
		dc.l Delete_Current_Sprite				; A9
		dc.l Delete_Current_Sprite				; AA
		dc.l Delete_Current_Sprite				; AB
		dc.l Delete_Current_Sprite				; AC
		dc.l Delete_Current_Sprite				; AD
		dc.l Delete_Current_Sprite				; AE
		dc.l Delete_Current_Sprite				; AF
		dc.l Delete_Current_Sprite				; B0
		dc.l Delete_Current_Sprite				; B1
		dc.l Delete_Current_Sprite				; B2
		dc.l Delete_Current_Sprite				; B3
		dc.l Delete_Current_Sprite				; B4
		dc.l Delete_Current_Sprite				; B5
		dc.l Delete_Current_Sprite				; B6
		dc.l Delete_Current_Sprite				; B7
		dc.l Delete_Current_Sprite				; B8
		dc.l Delete_Current_Sprite				; B9
		dc.l Delete_Current_Sprite				; BA
		dc.l Delete_Current_Sprite				; BB
		dc.l Delete_Current_Sprite				; BC
		dc.l Delete_Current_Sprite				; BD
		dc.l Delete_Current_Sprite				; BE
		dc.l Delete_Current_Sprite				; BF
		dc.l Delete_Current_Sprite				; C0
		dc.l Delete_Current_Sprite				; C1
		dc.l Delete_Current_Sprite				; C2
		dc.l Delete_Current_Sprite				; C3
		dc.l Delete_Current_Sprite				; C4
		dc.l Delete_Current_Sprite				; C5
		dc.l Delete_Current_Sprite				; C6
		dc.l Delete_Current_Sprite				; C7
		dc.l Delete_Current_Sprite				; C8
		dc.l Delete_Current_Sprite				; C9
		dc.l Delete_Current_Sprite				; CA
		dc.l Delete_Current_Sprite				; CB
		dc.l Delete_Current_Sprite				; CC
		dc.l Delete_Current_Sprite				; CD
		dc.l Delete_Current_Sprite				; CE
		dc.l Delete_Current_Sprite				; CF
		dc.l Delete_Current_Sprite				; D0
		dc.l Delete_Current_Sprite				; D1
		dc.l Delete_Current_Sprite				; D2
		dc.l Delete_Current_Sprite				; D3
		dc.l Delete_Current_Sprite				; D4
		dc.l Delete_Current_Sprite				; D5
		dc.l Delete_Current_Sprite				; D6
		dc.l Delete_Current_Sprite				; D7
		dc.l Delete_Current_Sprite				; D8
		dc.l Delete_Current_Sprite				; D9
		dc.l Delete_Current_Sprite				; DA
		dc.l Delete_Current_Sprite				; DB
		dc.l Delete_Current_Sprite				; DC
		dc.l Delete_Current_Sprite				; DD
		dc.l Delete_Current_Sprite				; DE
		dc.l Delete_Current_Sprite				; DF